// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Commitment, CommitmentData, CommitmentTableId } from "./tables/Commitment.sol";
import { HandCard, HandCardData, HandCardTableId } from "./tables/HandCard.sol";
