// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum GameState {
  Join,
  Shuffle,
  DealCards,
  DecryptForOthers,
  UploadSecret,
  Error,
  Finished
}
